---
# ConfigMap para variables de entorno de Microservicio2
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservicio2-config
  namespace: carloscabreravas-dev
data:
  MICROSERVICIO1_URL: "http://microservicio.carloscabreravas-dev.svc.cluster.local:5000"
  DEBUG: "false"
  APP_NAME: "Microservicio2 API"
  API_VERSION: "1.0.0"

 
---
# ServiceAccount para Microservicio2
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservicio2
  namespace: carloscabreravas-dev
 
---
# Deployment para Microservicio2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio2
  namespace: carloscabreravas-dev
  labels:
    app: microservicio2
    version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: microservicio2
  template:
    metadata:
      labels:
        app: microservicio2
    spec:
      serviceAccountName: microservicio2
      dnsPolicy: ClusterFirst
      containers:
      - name: microservicio2
        image: carloscabreravas/microservicio2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: http
          protocol: TCP     
        envFrom:
            - configMapRef:
                name: microservicio2-config
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
 
---
# Service para Microservicio2
apiVersion: v1
kind: Service
metadata:
  name: microservicio2
  namespace: carloscabreravas-dev
  labels:
    app: microservicio2
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: microservicio2
 
---
# Route para OpenShift - Microservicio2
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: microservicio2
  namespace: carloscabreravas-dev
  labels:
    app: microservicio2
spec:
  to:
    kind: Service
    name: microservicio2
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
 
---
# PodDisruptionBudget para alta disponibilidad
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: microservicio2-pdb
  namespace: carloscabreravas-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: microservicio2
 
---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservicio2-hpa
  namespace: carloscabreravas-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservicio2
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80